apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/btquanto/DockerVolumes/jupyter"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notebook-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notebook
  template:
    metadata:
      labels:
        app: notebook
    spec:
      containers:
        - name: notebook
          image: btquanto/jupyterlab:latest
          volumeMounts:
            - mountPath: /workspace # Mount point inside the container
              name: jupyter-volume
          ports:
            - containerPort: 8888
      volumes:
        - name: jupyter-volume
          persistentVolumeClaim:
            claimName: jupyter-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: jupyter-service
spec:
  selector:
    app: notebook
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 2701
      targetPort: 8888
      nodePort: 32709 # 30000 - 32767
